org.gradle.jvmargs = -Xmx4G

# Mod
minecraft_version = 1.21.1
forge_enabled = false
mod_version = 1.7.2
maven_group = dev.lazurite

# Fabric
fabric_loader_version = 0.16.10
fabric_api_version = 0.116.4+1.21.1

# Forge
forge_version = 47.1.0

# Dependencies
libbulletjme_version = 17.4.0
transporter_version = 1.4.0+1.21.1
toolbox_version = 1.4.0+1.21.1

# Gradle
shadow_version = 8.1.1
loom_version = 1.10.455
architectury_plugin_version = 3.4-SNAPSHOT