org.gradle.jvmargs = -Xmx4G
org.gradle.configuration-cache=false

# Mod
minecraft_version = 26.1.2
mod_version = 1.7.2
maven_group = dev.lazurite

# Fabric
fabric_loader_version = 0.19.3
fabric_api_version = 0.151.0+26.1.2

# Dependencies
libbulletjme_version = 17.4.0
transporter_version = 1.4.0+26.1.2
toolbox_version = 1.4.0+26.1.2

# Gradle
loom_version = 1.17.8
